from django.contrib import admin
from django.urls import path, include
from Aud_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.signin,name='signin'),
    path('signup',views.signup,name='signup'),
    path('otp_entering',views.otp_entering,name='otp_entering'),
    path('otp_sending',views.otp_sending,name='otp_sending'),
    path('home',views.home,name='home'),
    path('admin_home',views.admin_home,name='admin_home'),
    path('logg',views.logg,name='logg'),
    path('admin_users',views.admin_users,name='admin_users'),
    path('admin_orders', views.admin_orders, name='admin_orders'),
    path('admin_category',views.admin_category,name='admin_category'),
    path('admin_products',views.admin_products,name='admin_products'),
    path('admin_products_list',views.admin_products_list,name='admin_products_list'),
    path('product_edit/<int:pk>/',views.product_edit,name='product_edit'),
    path('unlist_product/<int:pk>/',views.unlist_product,name="unlist_product"),
    path('products/',views.products,name='products'),
    path('signout/',views.signout,name='signout'),
    path('user_block/<int:pk>/',views.user_block,name='user_block'),
    path('user_unblock/<int:pk>/',views.user_unblock,name='user_unblock'),
    path('item_page/<int:pk>/',views.item_page,name='item_page'),
    path('cart',views.Cart,name='cart'),
    path('admin_category_edit/<int:pk>/',views.admin_category_edit,name='admin_category_edit'),
    path('makeUnlist/<int:pk>/',views.makeUnlist,name='makeUnlist'),
    path('makeList/<int:pk>/',views.makeList,name='makeList'),
    path('user_profile',views.user_profile,name='user_profile'),
    path('increment_count/', views.increment_count, name='increment_count'),
    path('decrement_count/', views.decrement_count, name='decrement_count'),
    path('cart_delete/',views.cart_delete,name='cart_delete'),
    path('add_to_cart/', views.add_to_cart, name='add_to_cart'),
    path('edit_profile',views.edit_profile,name='edit_profile'),
    path('user_address/<int:pk>/',views.user_address,name='user_address'),
    path('add_to_cart2',views.add_to_cart2,name='add_to_cart2'),
    path('checkout',views.checkout,name='checkout'),
    path('order_confirm',views.order_confirm,name='order_confirm'),
    path('myorders',views.myorders,name='myorders'),
    path('change_password',views.change_password,name='change_password'),
    path('cancel_order/',views.cancel_order,name='cancel_order'),
    path('add_address',views.add_address,name='add_address'),
    path('add_address_from_checkout',views.add_address_from_checkout,name="add_address_from_checkout"),
    path('del_address/<int:pk>/',views.del_address,name="del_address"),
    path('admin_coupons',views.admin_coupons,name='admin_coupons'),
    path('admin_coupon_edit/<int:pk>/',views.admin_coupon_edit,name="admin_coupon_edit"),
    path('admin_coupon_delete/<int:pk>/',views.admin_coupon_delete,name="admin_coupon_delete"),
    path('invoice_pdf/<int:pk>/', views.invoice_pdf, name='invoice_pdf'),
    path('image_delete/',views.image_delete,name="image_delete"),
    path('check',views.check,name = 'check'),
    path('password_update',views.password_update,name="password_update"),
    path('otp_entering2',views.otp_entering2,name="otp_entering2"),
    path('order_details/',views.order_details,name="order_details"),
    path('razor_success/',views.razor_success,name="razor_success"),
    path('admin_offers',views.admin_offers,name="admin_offers"),
    path('admin_offerpage',views.admin_offerpage,name="admin_offerpage"),
    path('asr_excel' , views.export_to_excel , name="asr_excel"),
    path('asr_pdf' , views.export_to_pdf , name="asr_pdf"),
    path('my_wallet',views.my_wallet,name='my_wallet'),
    path('return_order/<int:pk>/',views.return_order,name='return_order'),
    path('wishlist',views.wishlist,name='wishlist'),
    path('aboutus',views.aboutus,name='aboutus'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)